language: node_js
node_js:
  - 5
  - 6
  - 7
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g mocha eslint
services: mongodb
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=test